# Generated by Django 4.2.5 on 2023-12-08 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period', to='app.period'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ganre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitobning_ganri', to='app.ganre'),
        ),
    ]
